Usage, connection via DSN, connection via connector
databricks/databricks-sql-go pull request #69
Opened 2022-12-07 22:11 UTC by mattdeekay

Package docs. Sections include:
- Usage
- Connection via DSN string
- Connection via connector object
- Query cancellation, timeout
- DirectResults?
- Logging

2022-12-08 03:47 UTC, andrefurlan-db commented
Add some info on data type support as well? Specially on structs, maps, and arrays; decimal.

2022-12-11 18:33 UTC, yunbodeng-db commented
@andrefurlan-db can you review this change? Thanks!

2022-12-12 17:03 UTC, andrefurlan-db requested changes

2022-12-12 18:45 UTC, mattdeekay commented on doc.go
> +TTypeId_BOOLEAN_TYPE      --> bool
Fair ~ will change

2022-12-13 02:03 UTC, andrefurlan-db commented on doc.go
> +  - ansi_mode: (Boolean string). Session statements will adhere to rules defined by ANSI SQL specification. Default is "false"
oh sorry, I think the default for data warehouses is `true`

2022-12-13 02:07 UTC, andrefurlan-db commented on doc.go
> +ARRAY<elementType> --> sql.RawBytes
maybe worth mentioning that ARRAY, STRUCT, MAP can be scanned to a string, in which will be like:
`{arrayVal:[1,2,3] mapVal:{"key1":1} structVal:{"string_field":"string_val","array_field":[4,5,6]}}`
And from there the user can unmarshal the JSON string to the appropriate type

2022-12-13 21:15 UTC, andrefurlan-db approved these changes

2022-12-13 21:23 UTC, merged